const Emoticon: Emoticon[] = [
  { key: '오', url: 'http://lt2.kr/image/con/5.gif' },
  { key: '^^7', url: 'http://lt2.kr/image/con/777.gif' },
  { key: '아', url: 'http://lt2.kr/image/con/ah.png' },
  { key: '...', url: 'http://lt2.kr/image/con/dot.gif' },
  { key: '엑', url: 'http://lt2.kr/image/con/eek.gif' },
  { key: '펀딩완료', url: 'http://lt2.kr/image/con/finish.gif' },
  { key: '입금완료', url: 'http://lt2.kr/image/con/finish2.gif' },
  { key: '평생', url: 'http://lt2.kr/image/con/forever.gif' },
  { key: '영원히 함께해요', url: 'http://lt2.kr/image/con/forevertogether.gif' },
  { key: '펀딩을 해야돼', url: 'http://lt2.kr/image/con/fund.gif' },
  { key: '펀딩', url: 'http://lt2.kr/image/con/funding.gif' },
  { key: '개추', url: 'http://lt2.kr/image/con/good.gif' },
  { key: '하', url: 'http://lt2.kr/image/con/ha.gif' },
  { key: '감사', url: 'http://lt2.kr/image/con/hello.gif' },
  { key: '서둘러야 돼요', url: 'http://lt2.kr/image/con/hurry.gif' },
  { key: '글쎄여', url: 'http://lt2.kr/image/con/idk.gif' },
  { key: '키타', url: 'http://lt2.kr/image/con/kita.gif' },
  { key: '아닌데요', url: 'http://lt2.kr/image/con/nope.gif' },
  { key: '그것이 약속이니까', url: 'http://lt2.kr/image/con/promise.gif' },
  { key: '평행우주', url: 'http://lt2.kr/image/con/pu.png' },
  { key: '지켜', url: 'http://lt2.kr/image/con/safe.gif' },
  { key: '회로는 느리게 펀딩은 빠르게', url: 'http://lt2.kr/image/con/slow.gif' },
  { key: '멈춰', url: 'http://lt2.kr/image/con/stop.gif' },
  { key: '분탕 멈춰', url: 'http://lt2.kr/image/con/stopit.gif' },
  { key: '감사합니다', url: 'http://lt2.kr/image/con/thx.gif' },
  { key: '너무해', url: 'http://lt2.kr/image/con/too.gif' },
  { key: '그쓰멍', url: 'http://lt2.kr/image/con/trash.gif' },
  { key: '재성함다', url: 'http://lt2.kr/image/con/wow.gif' },
  { key: '영차영차', url: 'http://lt2.kr/image/con/yungcha.gif' },
];

export default Emoticon;
